comptedb:
  image: mysql:latest
  volumes:
    -  /home/user/Desktop/gest-compte-bancaires:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: gest-compte-bancaires

version: '3.8'

services:
  discovery:
    image: openjdk:11-jre-slim
    command: ["java", "-jar", "/app/discovery.jar"]
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gest-compte-bancaires?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: my-secret-pw
    ports:
      - "8762:8762"
    volumes:
      - ./discovery/target:/app
  gateway:
    image: openjdk:11-jre-slim
    command: ["java", "-jar", "/app/gateway.jar"]
    depends_on:
      - discovery
      - customer-service
      - order-service
      - nodejs-service
    environment:
      DISCOVERY_SERVER_URL: http://discovery:8761/eureka/
    ports:
      - "8080:8080"
    volumes:
      - ./gateway/target:/app
  customer-service:
    image: openjdk:11-jre-slim
    command: ["java", "-jar", "/app/customer-service.jar"]
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/my_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: my-secret-pw
      SERVER_PORT: 8081
    volumes:
      - ./customer-service/target:/app
  order-service:
    image: openjdk:11-jre-slim
    command: ["java", "-jar", "/app/order-service.jar"]
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/my_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: my-secret-pw
      SERVER_PORT: 8082
    volumes:
      - ./order-service/target:/app
  nodejs-service:
    build: ./nodejs-service
    depends_on:
      - gateway
    ports:
      - "3000:3000"
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:


