version: "3.8"
services:
  eurekaserver:
    container_name: eurekaserver
    image: eureka:latest
    ports:
      - "8762:8762"
    networks:
      - eureka-server

  account:
    image: account:latest
    ports:
      - "8083:8083"
    networks:
      - eureka-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8762/eureka/
    depends_on:
      - eurekaserver

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    networks:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: account
    volumes:
      - mysql-data:/var/lib/mysql

  gateway:
    image: openjdk:11-jre-slim
    command: [ "java", "-jar", "/app/CompteService-0.0.1-SNAPSHOT.jar" ]
    depends_on:
      - account
      - eurekaserver
    networks:
      - eureka-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8762/eureka/
    ports:
      - "8081:8081"
    volumes:
      - ./gateway/target:/app

volumes:
  mysql-data:
networks:
  eureka-server:
    external: true
  mysql:
    driver: bridge


